### ISSUE TITLE
some sort of linting task

### ISSUE THREAD

**Issue by nexus-uw** [rangle/angular2-redux-starter#8] opened 2016-01-12 17:57 UTC

**Comment by SethDavenport** [comment] 2016-01-13 04:21
Linting is currently handled by webpack.  However it would be good for lint errors to fail a CI build.

One option is to adjust the `.tslintrc` to make eveything an error, and then use webpack's NoErrorsPlugin in dev mode to surface them as warnings.  This way the production `webpack -p` will fail on them, but `npm run dev` will treat them as warnings.

**Comment by SethDavenport** [comment] 2016-01-27 14:50
I've merged all the starter issues into one ZenHub board.  Marking this as a duplicate of https://github.com/rangle/angular-redux-starter/issues/9, so we address this uniformly across all the starters.

**Comment by SethDavenport** [comment] 2016-01-27 14:50
Merged board: https://github.com/rangle/react-redux-starter/pull/60#boards?repos=45710306,46129075,49850682,48808013,49800398

**Closed by SethDavenport** 2016-01-27 14:50 UTC
Labels: duplicate
